################################################################################
# Input configuration                                                          #
################################################################################

input:
  # Optional: input directory to use for fastq files (for local input files).
  dir: 'input'

  # Optional: configuration to use for remote (FTP) input files.
  # ftp:
  #   username: 'user'
  #   password: 'pass'


################################################################################
# Rule configuration                                                           #
################################################################################

cutadapt:
  # Parameter --length is required to trim reads to the read length
  # expected by the used qdnaseq reference. Can be omitted if reads
  # are already of the expected length.
  extra: >-
    --length 50
    -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
    --minimum-length 30

bwa_aln:
  index: '/path/to/index'
  extra: ''
  threads: 10

bwa_samse:
  index: '/path/to/index'
  # Note that MarkDuplicates requires the LB tag to be set.
  extra: "-r \"@RG\\tID:{sample}.{lane}\\tSM:{sample}\\tLB:{sample}\\t\
          PU:{sample}.{lane}\\tPL:ILLUMINA\\tCN:CENTRE\""
  sort_extra: ''

samtools_merge:
  extra: ''
  threads: 10

picard_mark_duplicates:
  extra: >-
    -XX:ParallelGCThreads=5
    VALIDATION_STRINGENCY=LENIENT

multiqc:
  extra: ''

fastqc:
  extra: ''

qdnaseq:
  genome: 'mm10'
  organism: 'other'
  bin_size: 50
  read_length: 50
  blacklists:
    - 'custom.bed'
