################################################################################
# Pipeline options                                                             #
################################################################################

options:
    # Read group information to use for BWA.
    readgroup:
        platform: ILLUMINA
        centre: CENTRE

    # QDNAseq configuration. Includes bin_size/read_length configuration,
    # which is shared between rules to ensure proper read lengths.
    qdnaseq:
        annotate: true
        bin_size: 50
        read_length: 50

    # Whether to run RUBIC/GISTIC.
    rubic: true
    gistic: true


################################################################################
# References                                                                   #
################################################################################

references:
    bwa_index: input/genome/Homo_sapiens.GRCh38.dna.primary_assembly.fa
    gtf: input/reference.gtf
    qdnaseq:
        genome: mm10
        organism: other
        blacklists: ["input/custom.bed"]
    rubic:
        # Biomart host/dataset to use for gene definitions.
        biomart_host: "http://www.ensembl.org/"
        biomart_dataset: hsapiens_gene_ensembl

        # Chromosomes to include in the analysis.
        chromosomes: [
            "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11",
            "12", "13", "14", "15", "16", "17", "18", "19","20","21","22","X"]

        # Chromosome mapping (to map chromosomes from the input to
        # match with the chromosome notation used in the biomart dataset).
        chromosome_map: ~

    gistic:
        # Gistic reference file.
        mat: input/gistic.mat

        # Chromosomes/mapping (same as for RUBIC).
        chromosomes: [
            "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11",
            "12", "13", "14", "15", "16", "17", "18", "19","20","21","22", "X"]
        chromosome_map: ~


################################################################################
# Rule-specific configuration                                                  #
################################################################################

rules:
    cutadapt:
        extra:
            - "-a AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
            - "--minimum-length 20"
        threads: 5
    bwa_aln:
        extra: []
        threads: 10
    bwa_samse:
        extra: []
        sort_extra: []
    samtools_merge:
        extra: []
        threads: 10
    picard_mark_duplicates:
        extra:
            - "-XX:ParallelGCThreads=5"
            - VALIDATION_STRINGENCY=LENIENT
    qdnaseq_annotate:
        extra:
            - "--impute"
            - "--one_based"
    multiqc:
        extra: []
    fastqc:
        extra: []
    rubic:
        fdr: 0.25
        focal_threshold: 1e+08
        min_probes: 4
    gistic:
        extra: []
        gistic_root: /path/to/gistic


################################################################################
# Input configuration                                                          #
################################################################################

input:
    # Input directory (unit paths are taken relative to this directory).
    dir: datos/HULP_*


################################################################################
# Sample (group) configuration                                                 #
################################################################################

# Samples are separated into samples and units, where multiple units are merged
# into a single sample. This allows to have data from more than one sequencing
# run or lane for a sample.

samples:
    S1: ["S1.HULP"]
    S2: ["S2.HULP"]

units:
    S1.HULP: ["HULP_1004_FKDN210100496-1A_HWNKLDSXY_L4_1.fq.gz"]
    S2.HULP: ["HULP_1009_FKDN210100497-1A_HWNKLDSXY_L4_1.fq.gz"]

# Normals are used to correct for artefacts that remain after the
# GC-content/mappability correction performed by QDNAseq.

normals: ["S1"]

# Sample groups are used by RUBIC/GISTIC to perform recurrence analyses
# on different subsets of samples.

groups:
    group1: ["S1", "S2"]
